### ISSUE TITLE
zmq version 23.0.0+

### ISSUE THREAD

**Issue by cgahr** [packagecontrol/pyzmq#1]
Hi,
for my package I need zmq version 23.0.0+.

Any change you can update this package?

BR, cgahr

**Comment by deathaxe** [comment]
Resolved by https://github.com/packagecontrol/channel/pull/23

This repository targets ST3 and python 3.3.

zmq 23.0 requires python 3.6

Any package using latest version, requires ST4 and needs to opt-in to python 3.8 plugin_host.
