### ISSUE TITLE
Missing Apple silicon (arm64) version

### ISSUE THREAD

**Issue by mattwidmann** [packagecontrol/pyzmq#2]
Now that Sublime Text 4 is compiled for ARM on Apple silicon devices, this package causes any dependent packages to fail to load because it lacks universal binaries (or an ARM variant). For how this impacts Helium, see https://github.com/sschuhmann/Helium/issues/146.

**Comment by deathaxe** [comment]
Resolved by https://github.com/packagecontrol/channel/pull/23

This repository targets ST3 and python 3.3.

ARM64 requires at least python 3.8 and thus ST4.
